title: portfolio # your name (or website title) here
logo: "/images/mainphoto.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I'm Jen, programmer & research data analyst.
  <br><br>
 This site showcases my data science projects. Feel free to explore and contact me with any questions.
  <br><br>
  <a href="https://www.linkedin.com/in/jarriaza/"><b>Connect via LinkedIn</a> 
  <br>
    <a href="https://instagram.com/zenjen.io">Follow @zenjen.io on Instagram</b></a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

