title: Jen Arriaza # your name (or website title) here
logo: "/images/profilephoto2.JPG?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
@zenjen-devs
  &nbsp;
  <br>
  <br>
  <b><h2>Hello! I'm Jen :seedling:</b></h2>
  <p>I analyze, visualize, & interpret data to decipher problems, make informed decisions, and explore outcomes.<br>
  <i>A bit of wizardy</i> :crystal_ball:
  <br>
  <br>
  <b>New York University '22</b></p>
  <br><br>
  
  <a href="https://www.linkedin.com/in/jarriaza/"><img src="https://image.flaticon.com/icons/png/128/174/174857.png" alt="lin_jarriaza" height="20" width="20" /></a> 
  &nbsp;
   
    <a href="https://instagram.com/zenjen.io"><img src="https://image.flaticon.com/icons/png/128/174/174855.png" alt="IG:zenjen.io" height="20" width="20" /></a>
  &nbsp;
    <a href="mailto:jen.arriaza@nyu.edu"><img src="https://seeklogo.com/images/G/gmail-new-2020-logo-32DBE11BB4-seeklogo.com.png" height="20" width="20" /></a> 
  &nbsp;
    <a href="https://github.com/jenarriaz"><img src="https://cdn.iconscout.com/icon/free/png-256/github-113-438180.png" height="22" width="22" /></a>
  <br>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
