title: Jen Arriaza # your name (or website title) here
logo: "/images/portfoliophoto1.jpg?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
  <br>
  <b>Hello! I'm Jen :seedling:</b> 
  <br>
  I analyze, visualize, and interpret data to decipher problems, make informed decisions, and explore outcomes.<br>
  A little bit of wizardy.
  <br>
  <br>
  <b>NYU-SPS '22, BSc. Applied Data Analytics & Visualization</b><i> (Final Year)</i>
  <br><br>
  
  <a href="https://www.linkedin.com/in/jarriaza/"><img src="https://image.flaticon.com/icons/png/128/174/174857.png" alt="lin_jarriaza" height="20" width="20" /></a> 
  &nbsp;
   
    <a href="https://instagram.com/zenjen.io"><img src="https://image.flaticon.com/icons/png/128/174/174855.png" alt="IG:zenjen.io" height="20" width="20" /></a>
  &nbsp;
    <a href="mailto:jen.arriaza@nyu.edu"><img src="https://seeklogo.com/images/G/gmail-new-2020-logo-32DBE11BB4-seeklogo.com.png" height="20" width="20" /></a> 
  &nbsp;
    <a href="https://github.com/jenarriaz"><img src="https://cdn.iconscout.com/icon/free/png-256/github-113-438180.png" height="22" width="22" /></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
