title: zenjen-devs # your name (or website title) here
logo: "/images/mainphoto.JPG?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! I'm Jen :seedling:
  <br>
  <b>Programmer & BSc. Data Science Senior at NYU ('22)</b> 
  <br><br>
  This site showcases my data science projects. Please explore and contact me with 
  any questions or comments.
  
  <br><br>
  <a href="https://www.linkedin.com/in/jarriaza/"><b>Connect via LinkedIn</b></a> 
  <br>
    <img src="https://image.flaticon.com/icons/png/128/174/174855.png" alt="IG:zenjen.io" height="20" width="20" /> <a href="https://instagram.com/zenjen.io">Follow @zenjen.io Instagram</b></a>
  <br>
    <a href="mailto:jen.arriaza@nyu.edu"><b> jen.arriaza@nyu.edu</b></a>  :mailbox:
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
