title: Jen Arriaza # your name (or website title) here
logo: "/images/pfpupdate2.png?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
  <br>
  <b><h2>Hello! I'm Jen :seedling:</b></h2>
  <p>I use data science to solve problems and build data-powered intelligent systems.<br>
  <br>

<i class="fa fa-linkedin-square" style="font-size:24px"></i>

  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
