title: zenjen-devs # your name (or website title) here
logo: "/images/mainphoto.JPG?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
  Hello! I'm Jen :seedling:
  <br>
  <b>Programmer & BSc. Data Science Senior at NYU ('22)</b> 
  <br><br>
  This site showcases my data science projects. Please explore and contact me with 
  any questions or comments.
  
  <br><br>
  <img src="https://image.flaticon.com/icons/png/128/174/174857.png" alt="lin_jarriaza" height="15" width="15" />
  <a href="https://www.linkedin.com/in/jarriaza/"><b>Connect via LinkedIn</b></a> 
  <br>
    <img src="https://image.flaticon.com/icons/png/128/174/174855.png" alt="IG:zenjen.io" height="15" width="15" /> 
    <a href="https://instagram.com/zenjen.io">Follow My Visual Blog on Instagram</b></a>
  <br>
  <img src="https://seeklogo.com/images/G/gmail-new-2020-logo-32DBE11BB4-seeklogo.com.png" height="15" width="15" />
    <a href="mailto:jen.arriaza@nyu.edu"><b> jen.arriaza@nyu.edu</b></a> 
  <br>
    <img src="https://cdn.iconscout.com/icon/free/png-256/github-113-438180.png" height="20" width="20" />
    <a href="https://github.com/jenarriaz">View on Github</b></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
