title: Jen Arriaza # your name (or website title) here
logo: "/images/pfp-update.jpg?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
  <br>
  <b><h2>Hello! I'm Jen :seedling:</b></h2>
  <p>I analyze, visualize, & interpret data to decipher problems, make informed decisions, and explore outcomes.<br>
  <br>
  <b>Navigate to my Github</b><br>
  <a href="https://github.com/jenarriaz"><img src="https://cdn.iconscout.com/icon/free/png-256/github-113-438180.png" height="22" width="22" /></a>
  &nbsp;
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
